### ISSUE TITLE
Unknown custom element: <picker-area> - did you register the component correctly? For recursive components

### ISSUE THREAD

**Issue by Roqii** [tungquach/vue-emoji-mart-picker#1]
![image](https://user-images.githubusercontent.com/5799590/48241777-3df86280-e413-11e8-916b-166a7002a9da.png)

I'm developing the project with Nuxt
But this happens with reference to 'vue-emoji-mart- picker'

**Comment by tungquach** [comment]
Hi @Roqii , did you register it on `components`:

```
<template>
  <div>
    <picker-area />
  </div>
</template>

<script>
  import PickerArea from 'vue-emoji-mart-picker'

  export default {
    components: {
      PickerArea,
    },
  }
</script>
```

**Comment by Roqii** [comment]
![image](https://user-images.githubusercontent.com/5799590/48297253-f808d080-e4de-11e8-875f-75363a67f67b.png)

![image](https://user-images.githubusercontent.com/5799590/48297257-0820b000-e4df-11e8-820c-847bdd50bf8c.png)

After registration,but the page CPU was 100% occupied, and the error "document is not defined" appeared

**Comment by tungquach** [comment]
@Roqii If you're using Nuxt, you might config it on client side plugin (https://nuxtjs.org/guide/plugins/#client-side-only) or use `no-ssr` component (https://nuxtjs.org/api/components-no-ssr#the-lt-no-ssr-gt-component)

**Comment by Roqii** [comment]
` 
   <no-ssr placeholder="Loading...">
      <picker-area />
    </no-ssr>
`
That's right. My problem was solved.
Thank you
